[server]
host = "0.0.0.0"   # The host address to bind to
port = 8080        # Default port (can be overridden by flag/env)
basepath = "/"     # For the case of a reverse proxy
max_sync_upload_size = "4MB" # Threshold for switching from RAM to Disk processing
cors_allowed_origins = []

[database]
# Relative or absolute path to the .db file (e.g., "mediahub.db")
source = "mediahub.db"

[storage.local]
root = "storage_root"

[logging]
level = "info" # Standard application logging level

[logging.audit]
type = "stdio" # Where to store audit logs: "stdio" or "database"
enabled = false # Toggle audit logging on or off
retention = "31d" # How long to keep audit logs (e.g., "7d" for 7 days)

[media]
# Optional: Path to the FFmpeg executable.
# If empty, the server will check the system PATH.
ffmpeg_path = ""

# Optional: Path to the FFprobe executable.
# If empty, the server will check near ffmpeg_path, then the system PATH.
ffprobe_path = ""

[auth.jwt]
# Token expiration settings
access_duration = "5min"
refresh_duration = "24h"

