package shared

import "time"

// CustomField defines a custom metadata field for a database.
type CustomField struct {
	Name string `json:"name"`
	Type string `json:"type"` // Supported types: TEXT, INTEGER, REAL, BOOLEAN
}

// CustomFields is a slice of CustomField.
type CustomFields []CustomField

// defines a role that a user has in a specific database (can_view, can_edit, can_delete, can_admin)
type Role struct {
	Database string `toml:"database"`
	Role     string `toml:"role"`
}

// Housekeeping defines the automated maintenance policies for a database.
// It is generated by parsing the config and used in the housekeeping service.
type Housekeeping struct {
	Interval  time.Duration
	DiskSpace uint64
	MaxAge    time.Duration
}
