// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Christian Dengler",
            "url": "https://www.swcd.lu",
            "email": "denglerchr@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revokes a Refresh Token, effectively logging the user out.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Logout",
                "parameters": [
                    {
                        "description": "Refresh token JSON body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tokenhandler.TokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Logged out successfully message",
                        "schema": {
                            "$ref": "#/definitions/utils.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/token": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Obtains an internal JWT Access/Refresh token pair.\nSupports two authentication methods:\n1. Local Authentication: Send standard Basic Auth headers.\n2. OIDC Token Exchange (commercial version only): Send a JSON body containing a valid external JWT (` + "`" + `idp_token` + "`" + `).\nProviding both methods in a single request will result in a 400 Bad Request.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Get a token pair",
                "parameters": [
                    {
                        "description": "OIDC Identity Provider Token (required if not using Basic Auth)",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/tokenhandler.OidcTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns access and refresh tokens",
                        "schema": {
                            "$ref": "#/definitions/tokenhandler.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Ambiguous authentication request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid credentials, invalid OIDC token, or missing authentication",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error or OIDC not available",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/token/refresh": {
            "post": {
                "description": "Uses a valid Refresh Token to obtain a new Access/Refresh token pair.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "Refresh token pair",
                "parameters": [
                    {
                        "description": "Refresh token JSON body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tokenhandler.TokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns new access and refresh tokens",
                        "schema": {
                            "$ref": "#/definitions/tokenhandler.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Invalid or expired refresh token",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/audit": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a paginated list of system audit logs. This endpoint provides basic filtering by timestamp and pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Get audit logs",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Number of logs to return (default 30)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order ('asc' or 'desc', default 'desc')",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Start timestamp (Unix milliseconds)",
                        "name": "tstart",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "End timestamp (Unix milliseconds)",
                        "name": "tend",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns an array of audit log objects",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/audithandler.AuditLogResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid parameter formats",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Requires IsAdmin role)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve audit logs",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Creates a new database with custom fields and a dedicated entry table.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Create a new database",
                "parameters": [
                    {
                        "description": "Database Metadata",
                        "name": "database",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/databasehandler.DatabaseCreatePayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/databasehandler.DatabaseResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload or missing name",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Database name already in use",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create database or storage folder",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/{database_id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retrieves details, custom fields, and statistics for a specific database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Get database details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/databasehandler.DatabaseResponse"
                        }
                    },
                    "400": {
                        "description": "Missing id path parameter",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to calculate stats",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Updates the mutable configuration fields for a specific database, including its name.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Update database housekeeping rules or rename",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Configuration and Housekeeping Rules",
                        "name": "housekeeping",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/databasehandler.DatabaseUpdatePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/databasehandler.DatabaseResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request payload or missing id path parameter",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to update database",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Deletes a database, its entry table, and all of its associated entries and metadata.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Delete a database",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "$ref": "#/definitions/utils.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Missing database_id path parameter",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to delete database record or folder",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/{database_id}/entries": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retrieves a paginated list of entries from a specific database. Only supports time-based filters.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Get entries from a database (basic)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Number of entries to return (default 30)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset for pagination (default 0)",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort order ('asc' or 'desc', default 'desc')",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Start timestamp (Unix milliseconds)",
                        "name": "tstart",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "End timestamp (Unix milliseconds)",
                        "name": "tend",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns an array of entry metadata objects",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entryhandler.EntryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing id param or invalid parameter formats",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Requires CanView role)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve entries",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/{database_id}/entries/delete": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Deletes multiple entries in a single atomic transaction. Updates database statistics only once.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Bulk delete entries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON object containing a list of Entry IDs to delete",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entryhandler.BulkDeleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Summary of the deletion operation",
                        "schema": {
                            "$ref": "#/definitions/entryhandler.BulkDeleteResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request, missing id, or empty IDs list",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Requires CanDelete role)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Transaction failed",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/{database_id}/entries/export": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Streams a ZIP archive containing the files and metadata (CSV) for the specified entries using io.Pipe.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/zip"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Export entries as ZIP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "List of Entry IDs to export",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entryhandler.ExportRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ZIP Archive containing files and entries.csv",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Missing id query parameter or empty IDs list",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Requires CanView role)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "ZIP streaming failed",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/{database_id}/entries/search": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retrieves a list of entry metadata matching the complex, nested filter criteria provided in the request body.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Search for entries in a database (complex)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON body defining filter, sort, and pagination logic",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/repository.SearchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns an array of matching results (even if empty)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/entryhandler.EntryResponse"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing id, invalid JSON, missing limit, or invalid filter/sort",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Requires CanView role)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/{database_id}/entry": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Uploads a new entry to a specified database using multipart/form-data. The metadata part should be a JSON object containing the entry's timestamp, and any custom fields.\nThe 'file' part's 'filename' in the Content-Disposition header will be extracted and saved.\n\nThis endpoint uses a hybrid model:\n- **Small files (\u003c= Configured Limit):** Processed synchronously. Returns ` + "`" + `201 Created` + "`" + ` with the full entry metadata.\n- **Large files (\u003e Configured Limit):** Processed asynchronously. Returns ` + "`" + `202 Accepted` + "`" + ` with a partial response. The client should poll ` + "`" + `GET /api/entry/meta` + "`" + ` until the ` + "`" + `status` + "`" + ` field is 'ready'.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Upload an entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "JSON metadata for the entry",
                        "name": "metadata",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Entry file",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "For small files (synchronous processing)",
                        "schema": {
                            "$ref": "#/definitions/entryhandler.EntryResponse"
                        }
                    },
                    "202": {
                        "description": "For large files (asynchronous processing)",
                        "schema": {
                            "$ref": "#/definitions/entryhandler.PartialEntryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "415": {
                        "description": "Unsupported entry format",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/{database_id}/entry/{id}": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retrieves all metadata for a single entry, including custom fields.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Get entry metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The full entry metadata object",
                        "schema": {
                            "$ref": "#/definitions/entryhandler.EntryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database or entry not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Deletes an entry file from disk and its metadata from the database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Delete an entry",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success message",
                        "schema": {
                            "$ref": "#/definitions/utils.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database or entry not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Updates an entry's mutable metadata, including custom fields, the 'timestamp' and the 'filename'.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Update entry metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "JSON object with fields to update",
                        "name": "updates",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/entryhandler.PostPatchEntryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The full, updated entry metadata object",
                        "schema": {
                            "$ref": "#/definitions/entryhandler.EntryResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database or entry not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/{database_id}/entry/{id}/file": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a raw entry file. Supports Content Negotiation (JSON vs Binary) and HTTP Range Requests (Streaming).",
                "produces": [
                    "application/octet-stream",
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Get an entry file",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Byte range request (e.g., bytes=0-1023)",
                        "name": "Range",
                        "in": "header"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Base64 encoded file data (if Accept: application/json)",
                        "schema": {
                            "$ref": "#/definitions/entryhandler.FileJSONResponse"
                        },
                        "headers": {
                            "Accept-Ranges": {
                                "type": "string",
                                "description": "bytes"
                            }
                        }
                    },
                    "206": {
                        "description": "Partial content (streaming response)",
                        "schema": {
                            "type": "file"
                        },
                        "headers": {
                            "Accept-Ranges": {
                                "type": "string",
                                "description": "bytes"
                            },
                            "Content-Range": {
                                "type": "string",
                                "description": "bytes start-end/total"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid request or ID format",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database or entry not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "File is currently processing",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "416": {
                        "description": "Range Not Satisfiable",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/{database_id}/entry/{id}/preview": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retrieves a 200x200 WebP preview of an entry. Supports Content Negotiation via Accept header.",
                "produces": [
                    "image/webp",
                    "application/json"
                ],
                "tags": [
                    "entry"
                ],
                "summary": "Get an entry preview",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "format": "int64",
                        "description": "Entry ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Base64 encoded preview data (if Accept: application/json)",
                        "schema": {
                            "$ref": "#/definitions/entryhandler.FileJSONResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database, entry, or preview not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/database/{database_id}/housekeeping": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Manually triggers the housekeeping maintenance task for a specific database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "Trigger database housekeeping",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Database ID",
                        "name": "database_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Returns a report of actions taken.",
                        "schema": {
                            "$ref": "#/definitions/databasehandler.HousekeepingResponse"
                        }
                    },
                    "400": {
                        "description": "Missing database_id path parameter",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden (Requires CanDelete role)",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Database not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Lock not acquired",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/databases": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    }
                ],
                "description": "Retrieves a list of all available databases and their statistics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "database"
                ],
                "summary": "List all databases",
                "responses": {
                    "200": {
                        "description": "Returns an empty array if no databases exist",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/databasehandler.DatabaseResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve databases",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/info": {
            "get": {
                "description": "Retrieves general information about the software, including version, uptime, and media tool availability.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "info"
                ],
                "summary": "Get server info",
                "responses": {
                    "200": {
                        "description": "Returns general backend information",
                        "schema": {
                            "$ref": "#/definitions/infohandler.InfoResponse"
                        }
                    }
                }
            }
        },
        "/me": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves the user record and their specific permissions for the currently authenticated user. Admins will receive an empty permissions array.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Retrieve current user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/userhandler.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates the password for the currently authenticated user. Requires the old password to verify identity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update current user's password",
                "parameters": [
                    {
                        "description": "Old and New Password",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userhandler.UpdateMePayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Password updated successfully",
                        "schema": {
                            "$ref": "#/definitions/utils.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body or missing fields",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication failed: invalid old password",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new user account and optionally defines their database permissions. Requires the global IsAdmin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "New user details and permissions",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userhandler.CreateUserPayload"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User successfully created",
                        "schema": {
                            "$ref": "#/definitions/userhandler.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid JSON body, missing fields, or duplicate database names",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden: Admin user not retrieved",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "User already exists",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a user account and cascades the deletion to remove their database permissions. Requires the global IsAdmin role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Delete a user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User successfully deleted",
                        "schema": {
                            "$ref": "#/definitions/utils.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Missing or invalid ID format",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden: Admin user not retrieved",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Cannot delete the last remaining admin user",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing user's global status, password, or database permissions. Permissions act as an Upsert/Replace operation. Requires the global IsAdmin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Update an existing user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/userhandler.UpdateUserPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User successfully updated",
                        "schema": {
                            "$ref": "#/definitions/userhandler.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Missing ID or invalid JSON body",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden: Admin user not retrieved",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Cannot remove last admin user",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BasicAuth": []
                    },
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves a list of all user accounts and their assigned database permissions. Requires the global IsAdmin role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "Retrieve all users",
                "responses": {
                    "200": {
                        "description": "List of users",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/userhandler.UserResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden: User lacks IsAdmin role",
                        "schema": {
                            "$ref": "#/definitions/utils.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "audithandler.AuditLogResponse": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "actor": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "id": {
                    "type": "integer"
                },
                "resource": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "databasehandler.ConfigPayload": {
            "type": "object",
            "properties": {
                "auto_conversion": {
                    "type": "string"
                },
                "create_preview": {
                    "type": "boolean"
                }
            }
        },
        "databasehandler.DatabaseCreatePayload": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/databasehandler.ConfigPayload"
                },
                "content_type": {
                    "type": "string"
                },
                "custom_fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/databasehandler.DatabaseCustomField"
                    }
                },
                "housekeeping": {
                    "$ref": "#/definitions/databasehandler.HousekeepingPayload"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "databasehandler.DatabaseCustomField": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "databasehandler.DatabaseResponse": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/databasehandler.ConfigPayload"
                },
                "content_type": {
                    "type": "string"
                },
                "custom_fields": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/databasehandler.DatabaseCustomField"
                    }
                },
                "housekeeping": {
                    "$ref": "#/definitions/databasehandler.DatabaseResponseHK"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "stats": {
                    "$ref": "#/definitions/databasehandler.DatabaseResponseStats"
                }
            }
        },
        "databasehandler.DatabaseResponseHK": {
            "type": "object",
            "properties": {
                "disk_space": {
                    "description": "e.g. \"10G\"",
                    "type": "string"
                },
                "interval": {
                    "description": "e.g.\"10min\"",
                    "type": "string"
                },
                "max_age": {
                    "description": "e.g. \"365d\"",
                    "type": "string"
                }
            }
        },
        "databasehandler.DatabaseResponseStats": {
            "type": "object",
            "properties": {
                "entry_count": {
                    "type": "integer"
                },
                "total_disk_space_bytes": {
                    "type": "integer"
                }
            }
        },
        "databasehandler.DatabaseUpdatePayload": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/databasehandler.ConfigPayload"
                },
                "housekeeping": {
                    "$ref": "#/definitions/databasehandler.HousekeepingPayload"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "databasehandler.HousekeepingPayload": {
            "type": "object",
            "properties": {
                "disk_space": {
                    "type": "string"
                },
                "interval": {
                    "type": "string"
                },
                "max_age": {
                    "type": "string"
                }
            }
        },
        "databasehandler.HousekeepingResponse": {
            "type": "object",
            "properties": {
                "database_id": {
                    "type": "string"
                },
                "database_name": {
                    "type": "string"
                },
                "entries_deleted": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "space_freed_bytes": {
                    "type": "integer"
                }
            }
        },
        "entryhandler.BulkDeleteRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "entryhandler.BulkDeleteResponse": {
            "type": "object",
            "properties": {
                "database_id": {
                    "type": "string"
                },
                "deleted_count": {
                    "type": "integer"
                },
                "errors": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "space_freed_bytes": {
                    "type": "integer"
                }
            }
        },
        "entryhandler.EntryResponse": {
            "type": "object",
            "properties": {
                "custom_fields": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "database_id": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "filesize": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "media_fields": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "mime_type": {
                    "type": "string"
                },
                "preview_filesize": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "entryhandler.ExportRequest": {
            "type": "object",
            "properties": {
                "ids": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "entryhandler.FileJSONResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "Base64 encoded string with data URI prefix",
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                }
            }
        },
        "entryhandler.PartialEntryResponse": {
            "type": "object",
            "properties": {
                "custom_fields": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "database_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "mime_type": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "entryhandler.PostPatchEntryRequest": {
            "type": "object",
            "properties": {
                "custom_fields": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "filename": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "infohandler.InfoResponse": {
            "type": "object",
            "properties": {
                "conversion_to": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "oidc": {
                    "$ref": "#/definitions/infohandler.OIDCConfig"
                },
                "service_name": {
                    "type": "string"
                },
                "uptime": {
                    "description": "Changed to reflect elapsed duration",
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "infohandler.OIDCConfig": {
            "type": "object",
            "properties": {
                "enabled": {
                    "type": "boolean"
                },
                "login_page_disabled": {
                    "type": "boolean"
                },
                "oidc_client_id": {
                    "type": "string"
                },
                "oidc_issuer_url": {
                    "type": "string"
                },
                "oidc_redirect_url": {
                    "type": "string"
                }
            }
        },
        "repository.Condition": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "operator": {
                    "description": "e.g., \"=\", \"\u003e\", \"\u003c\", \"LIKE\"",
                    "type": "string"
                },
                "value": {
                    "description": "'any' allows for strings, numbers, or booleans"
                }
            }
        },
        "repository.FilterGroup": {
            "type": "object",
            "properties": {
                "conditions": {
                    "description": "The individual rules",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/repository.Condition"
                    }
                },
                "operator": {
                    "description": "e.g., \"and\", \"or\"",
                    "type": "string"
                }
            }
        },
        "repository.Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "repository.SearchRequest": {
            "type": "object",
            "properties": {
                "filter": {
                    "$ref": "#/definitions/repository.FilterGroup"
                },
                "pagination": {
                    "$ref": "#/definitions/repository.Pagination"
                },
                "sort": {
                    "$ref": "#/definitions/repository.SortCriteria"
                }
            }
        },
        "repository.SortCriteria": {
            "type": "object",
            "properties": {
                "direction": {
                    "description": "\"asc\" or \"desc\"",
                    "type": "string"
                },
                "field": {
                    "type": "string"
                }
            }
        },
        "tokenhandler.OidcTokenRequest": {
            "type": "object",
            "properties": {
                "idp_token": {
                    "type": "string"
                }
            }
        },
        "tokenhandler.TokenRequest": {
            "type": "object",
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "tokenhandler.TokenResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "userhandler.CreateUserPayload": {
            "type": "object",
            "properties": {
                "is_admin": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/userhandler.DatabasePermission"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "userhandler.DatabasePermission": {
            "type": "object",
            "properties": {
                "can_create": {
                    "type": "boolean"
                },
                "can_delete": {
                    "type": "boolean"
                },
                "can_edit": {
                    "type": "boolean"
                },
                "can_view": {
                    "type": "boolean"
                },
                "database_id": {
                    "type": "string"
                }
            }
        },
        "userhandler.UpdateMePayload": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "userhandler.UpdateUserPayload": {
            "type": "object",
            "properties": {
                "is_admin": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/userhandler.DatabasePermission"
                    }
                }
            }
        },
        "userhandler.UserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/userhandler.DatabasePermission"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "utils.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "utils.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BasicAuth": {
            "type": "basic"
        },
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and a JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0.0-beta1",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "SWCD MediaHub-API",
	Description:      "This is a server for a image, audio and file storage with integrated web-ui.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
